json_keys:
  - name: iin
    keys: [iin, biin]
    replace: "{hmac}"
    normalize: digits

regex:
  - name: email
    pattern: '[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}'
    replace: "***@***"
